### ISSUE TITLE
The proposal about Dockerfile

### ISSUE THREAD

**Issue by atinfinity** [tier4/aichallenge_bringup#10]
There is the following description in [README.md](https://github.com/tier4/aichallenge_bringup/blob/b7135d9914d78daac54f2df8345d7112a93193f2/README.md#docker%E3%81%A7%E3%83%93%E3%83%AB%E3%83%89%E3%81%8C%E9%80%9A%E3%82%8B%E3%82%B9%E3%82%B3%E3%82%A2%E3%81%8C%E5%87%BA%E3%82%8B%E3%81%93%E3%81%A8%E3%82%92%E7%A2%BA%E8%AA%8D).

> on host machine running the simulator:
> ```
> python3 avoid.py
> ```

This scenario script depends on `lgsvl` package.  
So, I have another solution.   
If you add the following code to Dockerfile, we can run this script on Docker container.

```
RUN git clone https://github.com/lgsvl/PythonAPI.git -b 2020.01 && \
    cd PythonAPI && \
    pip3 install --user . && \
    pip3 install --user -e .
```

**Comment by hakuturu583** [comment]
This is just a example dockerfile for checking build and run test cases.
So, feel free to edit it.

**Comment by atinfinity** [comment]
Thank you for your reply. I understood.
