### ISSUE TITLE
Docker コンテナの使い方について

### ISSUE THREAD

**Issue by nonanonno** [tier4/aichallenge_bringup#12]
記載されている[手順](https://github.com/tier4/aichallenge_bringup#docker%E3%81%A7%E3%83%93%E3%83%AB%E3%83%89%E3%81%8C%E9%80%9A%E3%82%8B%E3%82%B9%E3%82%B3%E3%82%A2%E3%81%8C%E5%87%BA%E3%82%8B%E3%81%93%E3%81%A8%E3%82%92%E7%A2%BA%E8%AA%8D) に従い コンテナの起動及びROSの起動を行うと通信が大きく遅延しているような挙動になります。

- 同様の現象がオンライン環境で発生していないか
- 対処方法をご存知であればその方法

をご確認お願いいたします。

## 手元での動作環境

- OS : Ubuntu 18.04
- GPU : GTX1080
- NVIDIA Driver : 440.84
- docker : 19.03.8

## 確認方法

README の手順の通りです。シミュレータは同一マシンで起動しています。

## 確認したこと

- コンテナ起動時に `--privileged` をつけると遅延は起こらず正常に動作する
- ローカルループバックの通信を見たところ、(正常に動作する)`--privileged` をつけた状態では 25MiB/s、つけていないと 15MiB/s と、通信速度に違いがでている。

**Comment by hakuturu583** [comment]
when we evaluate in the cloud, we run simulation with --priviraged option.
We will update documentation, sorry.

**Comment by nonanonno** [comment]
ご確認ありがとうございます。
