### ISSUE TITLE
Filename of vehicle setting is incorrect

### ISSUE THREAD

**Issue by atinfinity** [tier4/aichallenge_bringup#2]
In [README.md](https://github.com/tier4/aichallenge_bringup/blob/master/README.md), there is the following description.

> Bridge TypeにROSを選択、本レポジトリのdata以下にあるlexus.jsonの中身をSensorsに貼り付ける

But, actual filename is [leuxs.json](https://github.com/tier4/aichallenge_bringup/blob/master/data/leuxs.json).

**Comment by hakuturu583** [comment]
Sorry.
filename was incorrect

**Comment by hakuturu583** [comment]
Fixed.
