### ISSUE TITLE
Could not launch scenario scripts

### ISSUE THREAD

**Issue by atinfinity** [tier4/aichallenge_bringup#3]
I tried to launch the following scenario scripts.
But, I could not launch scenario scripts.
https://github.com/tier4/aichallenge_bringup/tree/master/scenario

So, I changed the specification of IP address to launch scenario scripts.

```diff
- agent.connect_bridge("10.100.2.0", 9090)
+ agent.connect_bridge(os.environ.get("BRIDGE_HOST", "127.0.0.1"), 9090)
```

**Comment by hakuturu583** [comment]
Thanks！　
I will fix it.

**Comment by hakuturu583** [comment]
Fixed
