### ISSUE TITLE
data/saved_waypoints.csv についての質問

### ISSUE THREAD

**Issue by nonanonno** [tier4/aichallenge_bringup#7]
`data/saved_waypoints.csv` を読み込んだところ、設定されているwaypoint は数メートル先までのようでした。これについて、

- このファイルを使って走行することが想定されるのか
- そうでなければ、どこをゴールに走行することが想定されるのか
   - オンライン環境では他車の位置が違うため

を確認したいです。
よろしくお願いいたします。

**Comment by hakuturu583** [comment]
このファイルを使って走行することが想定されるのか

想定しておりません。
こちらはあくまでサンプルであり、評価環境においてそのまま実行しても0点になるように調整してあります。

**Comment by hakuturu583** [comment]
そうでなければ、どこをゴールに走行することが想定されるのか

こちらはルールに記述されております。
確認よろしくお願いいたします。
https://www.jsae.or.jp/jaaic/rule.html

**Comment by hakuturu583** [comment]
このファイルを使って走行することが想定されるのか

想定しておりません。
こちらはあくまでサンプルであり、そのままでは点数が出ない経路になっております。

**Comment by hakuturu583** [comment]
ルールに関してはここに記述がございます。
https://www.jsae.or.jp/jaaic/rule.html

不明点がございましたらQ & Aの方まで連絡よろしくお願いいたします。

**Comment by nonanonno** [comment]
承知いたしました。ありがとうございます。
