### ISSUE TITLE
How to launch ROS node on official Docker container

### ISSUE THREAD

**Issue by atinfinity** [tier4/aichallenge_bringup#9]
There is the following description in [README.md](https://github.com/tier4/aichallenge_bringup/blob/b7135d9914d78daac54f2df8345d7112a93193f2/README.md#docker%E3%81%A7%E3%83%93%E3%83%AB%E3%83%89%E3%81%8C%E9%80%9A%E3%82%8B%E3%82%B9%E3%82%B3%E3%82%A2%E3%81%8C%E5%87%BA%E3%82%8B%E3%81%93%E3%81%A8%E3%82%92%E7%A2%BA%E8%AA%8D).

```shell
. ~/aichallenge_ws/install/setup.bash
roslaunch aichallenge_bringup aichallenge_bringup.launch avoid:=true
```

But, I could not run `roslaunch`. So, I think I should run the following command.

```shell
source ~/Autoware/install/setup.bash
source ~/aichallenge_ws/install/setup.bash
roslaunch aichallenge_bringup aichallenge_bringup.launch avoid:=true
```

Is my understanding correct?

**Comment by hakuturu583** [comment]
Yes, in order to install autoware an launch nodes in Autoware, we have to run setup.bash in the Autoware workspace.

**Comment by atinfinity** [comment]
@hakuturu583 Thank you for your reply. Could you please update README?

**Comment by hakuturu583** [comment]
@kokosabu Thank you for sending PR.
I will updete soon.
